apiVersion: apps/v1
kind: Deployment
metadata:
  name: golangmondaydemo
spec:
  replicas: 3
  selector:
    matchLabels:
      name: golangmondaydemo
  template:
    metadata:
      labels:
        name: golangmondaydemo
    spec:
      containers:
      - image: njclabslimitedcontainerreg.azurecr.io/njclabslimitedcontainerrepo:golangmondaydemo
        name: njclabslimitedcontainerreg
        ports:
          - containerPort: 8081
      imagePullSecrets: 
      - name: golangmondaydemosecret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: golangmondaydemo-service
spec:
  type: LoadBalancer
  selector:
    name: golangmondaydemo
  ports:
  - name: http  
    port: 80
    targetPort: 8081
